---
- name: Update all packages
  apt: upgrade=dist
  become: yes

- name: install basic packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'vim', 'docker', 'containerd', 'libxslt1-dev', 'libxml2-dev', 'zip', 'libssl-dev', 'unzip', 'python3-pip', 'python3-psycopg2', 'apg', 'mercurial', 'git', 'python-dev', 'python3-apt']

- name: install docker packages
  apt:
    name: ['docker.io','docker-compose']
