---
- name: edit postgres config for remote access
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "^#listen_addresses = 'localhost'.*$"
    line: "listen_addresses = '*' # what IP address(es) to listen on;"
    state: present 
