---
- name: edit postgres config for remote connections
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: "^# TYPE  DATABASE        USER            ADDRESS                 METHOD$"
    line: "host    all             postgres          0.0.0.0/0                trust"
