---
- name: installing postgresql
  become: yes
  apt:
    name: ['postgresql', 'postgresql-contrib']

- name: enable remote database connections
  include: enable-remote-connections.yaml

- name: enable remote database access
  include: enable-remote-access.yaml
