- name: set airflow metadata db to local postgres
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^sql_alchemy_conn = sqlite:.*$'
    line: 'sql_alchemy_conn = postgres://airflow:airflow@localhost:5432'
    state: present

- name: airflow config do not load example dags
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^load_examples = True.*$'
    line: 'load_examples = False'
    state: present

